#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory



echo "Meshing with blockMesh"
blockMesh > log.blockMesh

echo "Block decomposition with decomposePar"
decomposePar -cellDist > log.decomposePar

echo "Solving with rhoCentralFoam"
mpirun -np 6 rhoCentralFoam -parallel > log.rhoCentralFoam

echo "Block reconstruction with reconstructPar"
reconstructPar > log.reconstructPar


#------------------------------------------------------------------------------
